/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.co.indocyber.guessgame;

import java.io.IOException;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class GuesswingGame extends javax.swing.JFrame {
    
    WordModel modelWord;
    //String[] bankSoal= {"Pondok Indah","Sudirman","Tugu Tani","Citos"};
    WordModel soal1= new WordModel("Pondok Indah", "daerah jakarta selatan");
    WordModel soal2= new WordModel("Sudirman", "Jalan Utaman dijakarta");
    WordModel soal3= new WordModel("Tugu Tani", "Patung Dekat Monas");
    WordModel soal4= new WordModel("Citos", "Mall di jakarta selatan");
  
   // WordModel[] bankSoal = {soal1,soal2,soal3,soal4};
    
    List<WordModel>bankSoal;

    /**
     * Creates new form GuesswingGame
     */
    public GuesswingGame() throws IOException {
        bankSoal= WordQuestionGenerator.createQuestionFromFile("C:/Java_Latihan/question.txt");
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSoal = new javax.swing.JTextField();
        txtJawab = new javax.swing.JTextField();
        btPeriksa = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lComment = new javax.swing.JLabel();
        btMulai = new javax.swing.JButton();
        btClue = new javax.swing.JButton();
        lhint = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("             ........::::::: ~~~Tebak Kata ~~ ::::::..........");
        setMaximumSize(new java.awt.Dimension(400, 350));
        setMinimumSize(new java.awt.Dimension(400, 350));
        setPreferredSize(new java.awt.Dimension(400, 350));
        setResizable(false);
        getContentPane().setLayout(null);

        txtSoal.setEditable(false);
        txtSoal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoalActionPerformed(evt);
            }
        });
        getContentPane().add(txtSoal);
        txtSoal.setBounds(140, 130, 170, 31);
        getContentPane().add(txtJawab);
        txtJawab.setBounds(140, 180, 170, 31);

        btPeriksa.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        btPeriksa.setForeground(new java.awt.Color(153, 51, 0));
        btPeriksa.setText("Periksa");
        btPeriksa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPeriksaActionPerformed(evt);
            }
        });
        getContentPane().add(btPeriksa);
        btPeriksa.setBounds(120, 230, 90, 25);

        jLabel1.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 51, 0));
        jLabel1.setText("Jawaban");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(80, 180, 57, 23);

        lComment.setFont(new java.awt.Font("Book Antiqua", 1, 24)); // NOI18N
        lComment.setForeground(new java.awt.Color(255, 204, 0));
        lComment.setText("Belum Ada Jawaban");
        lComment.setMaximumSize(new java.awt.Dimension(400, 200));
        lComment.setMinimumSize(new java.awt.Dimension(400, 200));
        lComment.setPreferredSize(new java.awt.Dimension(400, 200));
        getContentPane().add(lComment);
        lComment.setBounds(80, 270, 254, 26);

        btMulai.setFont(new java.awt.Font("Book Antiqua", 1, 18)); // NOI18N
        btMulai.setForeground(new java.awt.Color(153, 51, 0));
        btMulai.setText("Mulai");
        btMulai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMulaiActionPerformed(evt);
            }
        });
        getContentPane().add(btMulai);
        btMulai.setBounds(170, 60, 106, 31);

        btClue.setFont(new java.awt.Font("Book Antiqua", 1, 12)); // NOI18N
        btClue.setForeground(new java.awt.Color(153, 51, 0));
        btClue.setText("Clue");
        btClue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClueActionPerformed(evt);
            }
        });
        getContentPane().add(btClue);
        btClue.setBounds(220, 230, 90, 25);

        lhint.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        lhint.setForeground(new java.awt.Color(0, 0, 204));
        getContentPane().add(lhint);
        lhint.setBounds(140, 100, 170, 20);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 51, 0));
        jLabel2.setText("Kata");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 130, 55, 31);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("Tebak Kata Acak");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(90, 0, 220, 64);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/id/co/indocyber/guessgame/images (1).jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(400, 200));
        jLabel4.setMinimumSize(new java.awt.Dimension(400, 200));
        jLabel4.setPreferredSize(new java.awt.Dimension(400, 200));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, -30, 400, 360);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMulaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMulaiActionPerformed
        // TODO add your handling code here:
        
        int soalIndex = (int) Math.floor(Math.random() * bankSoal.size());
        System.out.println("Index: " + soalIndex);
        modelWord= bankSoal.get(soalIndex);
//       modelWord = bankSoal[soalIndex]; 
        System.out.println(modelWord.getBasicWord());
       txtSoal.setText(modelWord.acakHuruf());
       
        
//        basicWord = basicWord.toUpperCase();
//        String[]arrayOfword=basicWord.split("");
//        
//        System.out.println("Huruf Ketiga : " + arrayOfword[2]);
//        
//        
//        for (int i = 0; i < arrayOfword.length; i++) {
//            System.out.println(arrayOfword[i]);
//            
//        }
//    
//        Arrays.sort(arrayOfword);
//        StringBuilder sb = new StringBuilder();
//        System.out.println("\nSetelah di Sort\n");
//        for (int i = 0; i < arrayOfword.length; i++) {
//           // System.out.println(arrayOfword[i]);
//           
//            sb.append(arrayOfword[i]);
//        }
//        
//        String soal = sb.toString();
////        System.out.println("Soal yang harus di jawab: " + soal.trim()); 
//        txtSoal.setText(soal.trim());
    }//GEN-LAST:event_btMulaiActionPerformed

    private void btPeriksaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPeriksaActionPerformed
        // TODO add your handling code here:
        String jawaban = txtJawab.getText().trim();
        modelWord.setJawaban(jawaban);
        if(modelWord.cekJawaban()){
        lComment.setText("Jawaban Anda Benar");
        }else {
            lComment.setText("Coba lagi");
        
        }
    }//GEN-LAST:event_btPeriksaActionPerformed

    private void txtSoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoalActionPerformed

    private void btClueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClueActionPerformed
        // TODO add your handling code here:
        lhint.setText(modelWord.getHint());
    }//GEN-LAST:event_btClueActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuesswingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuesswingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuesswingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuesswingGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new GuesswingGame().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(GuesswingGame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClue;
    private javax.swing.JButton btMulai;
    private javax.swing.JButton btPeriksa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lComment;
    private javax.swing.JLabel lhint;
    private javax.swing.JTextField txtJawab;
    private javax.swing.JTextField txtSoal;
    // End of variables declaration//GEN-END:variables
}
